### ISSUE TITLE
Update console message after build

### ISSUE THREAD

**Issue by vigmond** [myokit/myokit#648]
Some feedback would be helpful. I see that you can jump to last error but it would be nice to know that there are no errors, or  get a list of errors.

**Comment by MichaelClerx** [comment]
There's a "Validate model and protocol" option in the menu, under Run (Ctrl+B, for "build"), as well as the jump to last error option.

As long as there are errors this will print them in the console, if there are no errors it should show something like "[12:18:21] No errors found in model definition." or "[12:18:56] No changes to model since last build."
This can show you all sorts of errors, from missing or malformed equations to cyclical dependencies and such.

![Screenshot from 2020-10-10 12-21-15](https://user-images.githubusercontent.com/517644/95653787-3a841f00-0af3-11eb-9331-3b0c1be42154.png)

Another validation you might want to try is unit checking (under "Analysis", or simply hit F9).

Both validation methods will show you one error at a time, rather than a list of errors I'm afraid (as that type of parser is much harder to write, and will inevitably show a lot of false negatives too, i.e. errors caused by previous errors)

**Comment by MichaelClerx** [comment]
I guess the message `No changes to model since last build` could be changed to indicate the last build had no errors!
